### ISSUE TITLE
Reference keys starting with underscore don't work

### ISSUE THREAD

**Issue by stefanprobst** [tpoisot/autocomplete-citeproc#11]
Hi thanks for this amazing package!

The only thing that is not working for me atm are reference-keys starting with an underscore (@_title_2016). (I also checked with autocomplete-bibtex, didn't work there either).

**Comment by tpoisot** [comment]
Thanks for the feedback. 

Just some notes for myself:

- it works when using author names even if there is a `_` as the first key char
- keys starting with `_` are detected but the popup do not show

**Comment by tpoisot** [comment]
This is because both the searching and sorting is done on author names. I was thinking about adding options to search on title and keys (see #7) but this is lower priority at the moment.
