### ISSUE TITLE
Merge back to autocomplete bibtex?

### ISSUE THREAD

**Issue by mangecoeur** [tpoisot/autocomplete-citeproc#12]
@tpoisot - @apcshields added me to the autocomplete bibtex project as an collaborator with the idea to get a new release out. I'd be keen to un-fork the project - the master branch has citerproc support in it but probably needs testing and maybe some re-merging with changes you might have made more recently.

Perhaps if you were able to successfully merge autocomplete-bibtex/master with your project that would get us a long way there?

**Comment by tpoisot** [comment]
No time to do that, sorry.
