### ISSUE TITLE
error: Unexpected end of of JSON input

### ISSUE THREAD

**Issue by rriemann** [tpoisot/autocomplete-citeproc#16]
Hello,

I get the error "Unexpected end of of JSON input" if the Zotero BetterBibTex plugin (https://github.com/retorquere/zotero-better-bibtex) updates my json file.

Using the debugger, I found out that the file watcher is triggered twice:

- Once with an empty file. The string `content` below lets `JSON.parse()` fail.
- Then with a non-empty file. Here, everything is fine.

My atom version: "1.23.1"
I have all autocomplete-citeproc updates installed.

```coffee
 addBibtexFile: (file) ->
    return new Promise((resolve, reject) =>
      fs.readFile(file, 'utf8').then( (content) =>

        references = JSON.parse(content)
```

![screenshot_20180129_212640](https://user-images.githubusercontent.com/111932/35532621-208648be-053b-11e8-9dbc-4b02e21ade02.png)

**Comment by rriemann** [comment]
I am not sure if this should be better resolved upstream in https://github.com/retorquere/zotero-better-bibtex/ . @retorquere ?

**Comment by retorquere** [comment]
I'll see what I can do, but I don't actually export these files myself, I just schedule that Zotero does. In principle a manual export should exhibit the same problem.

**Comment by tpoisot** [comment]
I haven't been able to reproduce this, can you check that it's still happening with the `1.4.3` version of autocomplete-bibtex?

**Comment by tpoisot** [comment]
This was caused by the `issued` date field having a `literal` field, this will be fixed in the coming release.
